server:
  port: 8083
  servlet:
    application-display-name: mpos
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000
    accesslog:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://39.106.199.162:3306/bmps?characterEncoding=utf8&useSSL=false
    username: bmps
    password: bMps#89sd!Kl@6
    driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml

